In [4]:
import csv

In [18]:
with open("movies_dataset.csv") as f:
    data = list(csv.reader(f))
    header = data[0]
    data = data[1:]
    print(header)
    print(data)

['Title', 'Industry', 'Year', 'Rating', 'Budget', 'Studio', 'Revenue', 'Language']

In [23]:
import pandas as pd

In [25]:
df = pd.read_csv("movies_dataset.csv")

In [26]:
df

,Title,Industry,Year,Rating,Budget,Studio,Revenue,Language
0,Silent Whisper,Tollywood,1988,6.9,44.05,Mythri Movie Makers,190.65,Telugu
1,Iron Dream,Tollywood,1982,6.1,9.78,Mythri Movie Makers,13.24,Telugu
2,Lost Promise,Bollywood,2015,8.2,1.72,Dharma Productions,12.70,Hindi
3,Iron Kingdom,Kollywood,2017,7.2,50.03,AGS Entertainment,92.21,Tamil
4,Silent Journey,Kollywood,2001,5.7,18.60,AGS Entertainment,65.35,Tamil
...,...,...,...,...,...,...,...,...
995,Golden Symphony Rising,Mollywood,2020,6.0,25.45,Aashirvad Cinemas,12.74,Malayalam
996,Hidden Legacy Rising,Lollywood,2018,9.4,37.89,Six Sigma Plus,219.76,Punjabi
997,Lost Star Rising,Hollywood,1992,5.0,79.72,Columbia Pictures,33.19,English
998,Sacred River Origins,Bollywood,2006,6.6,50.25,Red Chillies Entertainment,284.33,Hindi
999,Last Voyage Origins,Kollywood,2013,8.4,50.68,Lyca Productions,201.36,Tamil

In [29]:
df.Rating.min() , df.Rating.max() , df.Rating.mean()

(np.float64(2.7), np.float64(10.0), np.float64(6.370100000000001))

In [33]:
df_b = df[df.Industry=="Bollywood"]

In [37]:
df_h = df[df.Industry=="Hollywood"]

df_m = df[df.Industry=="Mollywood"]

df_t = df[df.Industry=="Tollywood"]

In [38]:
df_b.Rating.min() , df_b.Rating.max() , df_b.Rating.mean()

(np.float64(2.8), np.float64(9.2), np.float64(6.330639730639731))

In [41]:
print("Bollywood min = ",df_h.Rating.min() ,"Bollywood max = ", df_h.Rating.max() , "Bollywood mean = ",df_h.Rating.mean() )

Bollywood min =  2.7 Bollywood max =  10.0 Bollywood mean =  6.379032258064516

In [43]:
df.columns

Index(['Title', 'Industry', 'Year', 'Rating', 'Budget', 'Studio', 'Revenue',
       'Language'],
      dtype='object')

In [45]:
df.Industry.unique()

array(['Tollywood', 'Bollywood', 'Kollywood', 'Hollywood', 'Sandalwood',
       'Mollywood', 'Lollywood'], dtype=object)

In [48]:
df.Language.unique()

array(['Telugu', 'Hindi', 'Tamil', 'English', 'Kannada', 'Malayalam',
       'Punjabi'], dtype=object)

In [50]:
df['Language'].unique()

array(['Telugu', 'Hindi', 'Tamil', 'English', 'Kannada', 'Malayalam',
       'Punjabi'], dtype=object)

In [52]:
df.Industry.value_counts()

Industry
Bollywood     297
Hollywood     248
Kollywood     130
Tollywood     128
Sandalwood     79
Mollywood      74
Lollywood      44
Name: count, dtype: int64

In [53]:
pwd

'C:\\code\\pandas'

In [54]:
df.columns

Index(['Title', 'Industry', 'Year', 'Rating', 'Budget', 'Studio', 'Revenue',
       'Language'],
      dtype='object')

In [56]:
df.Language.value_counts()

Language
Hindi        297
English      248
Tamil        130
Telugu       128
Kannada       79
Malayalam     74
Punjabi       44
Name: count, dtype: int64

In [58]:
df_new = df[['Title', 'Industry','Rating']]

In [62]:
df.max().Year

np.int64(2025)

In [66]:
df_year20 = df[df.Year>2000]

In [67]:
df_year20

,Title,Industry,Year,Rating,Budget,Studio,Revenue,Language
2,Lost Promise,Bollywood,2015,8.2,1.72,Dharma Productions,12.70,Hindi
3,Iron Kingdom,Kollywood,2017,7.2,50.03,AGS Entertainment,92.21,Tamil
4,Silent Journey,Kollywood,2001,5.7,18.60,AGS Entertainment,65.35,Tamil
5,Sacred Legacy Part II,Bollywood,2002,5.7,26.20,T-Series,55.53,Hindi
6,Golden Echo,Tollywood,2004,5.1,17.88,Mythri Movie Makers,43.74,Telugu
...,...,...,...,...,...,...,...,...
994,Shadow Whisper Part II,Mollywood,2004,7.3,12.66,Century Films,48.64,Malayalam
995,Golden Symphony Rising,Mollywood,2020,6.0,25.45,Aashirvad Cinemas,12.74,Malayalam
996,Hidden Legacy Rising,Lollywood,2018,9.4,37.89,Six Sigma Plus,219.76,Punjabi
998,Sacred River Origins,Bollywood,2006,6.6,50.25,Red Chillies Entertainment,284.33,Hindi
999,Last Voyage Origins,Kollywood,2013,8.4,50.68,Lyca Productions,201.36,Tamil

In [68]:
df.describe()

              Year       Rating       Budget      Revenue
count  1000.000000  1000.000000  1000.000000  1000.000000
mean   2002.948000     6.370100    58.272400   203.609310
std      13.212641     1.157885    67.859826   280.762128
min    1980.000000     2.700000     0.500000     0.950000
25%    1992.000000     5.600000    18.145000    43.402500
50%    2003.000000     6.400000    36.925000   110.640000
75%    2015.000000     7.200000    56.202500   230.135000
max    2025.000000    10.000000   298.270000  1974.090000

In [69]:
df

,Title,Industry,Year,Rating,Budget,Studio,Revenue,Language
0,Silent Whisper,Tollywood,1988,6.9,44.05,Mythri Movie Makers,190.65,Telugu
1,Iron Dream,Tollywood,1982,6.1,9.78,Mythri Movie Makers,13.24,Telugu
2,Lost Promise,Bollywood,2015,8.2,1.72,Dharma Productions,12.70,Hindi
3,Iron Kingdom,Kollywood,2017,7.2,50.03,AGS Entertainment,92.21,Tamil
4,Silent Journey,Kollywood,2001,5.7,18.60,AGS Entertainment,65.35,Tamil
...,...,...,...,...,...,...,...,...
995,Golden Symphony Rising,Mollywood,2020,6.0,25.45,Aashirvad Cinemas,12.74,Malayalam
996,Hidden Legacy Rising,Lollywood,2018,9.4,37.89,Six Sigma Plus,219.76,Punjabi
997,Lost Star Rising,Hollywood,1992,5.0,79.72,Columbia Pictures,33.19,English
998,Sacred River Origins,Bollywood,2006,6.6,50.25,Red Chillies Entertainment,284.33,Hindi
999,Last Voyage Origins,Kollywood,2013,8.4,50.68,Lyca Productions,201.36,Tamil