In [3]:
import pandas as pd

In [12]:
df = pd.read_csv("stock_data.csv")

In [13]:
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [24]:
df = pd.read_csv("stock_data.csv", header=1 ,names = ["Company", "eps","income","Rate","Founder"], nrows =4)
df

  Company            eps  income  Rate        Founder
0   GOOGL          27.82      87   845     larry page
1     WMT           4.61     484    65           n.a.
2    MSFT             -1      85    64     bill gates
3    RIL   not available      50  1023  mukesh ambani

In [31]:
df = pd.read_csv("stock_data.csv", header=1 ,names = ["Company", "eps","income","Rate","Founder"],na_values = {
    "eps":["not available"],
    "income":[-1],
    "Founder":["not available","n.a."] 
})
df

  Company    eps  income  Rate        Founder
0   GOOGL  27.82    87.0   845     larry page
1     WMT   4.61   484.0    65            NaN
2    MSFT  -1.00    85.0    64     bill gates
3    RIL     NaN    50.0  1023  mukesh ambani
4    TATA   5.60     NaN  n.a.     ratan tata

In [34]:
df = pd.read_csv("stock_data.csv", header=1 ,names = ["Company", "eps","income","Rate","Founder"], na_values = ["not available",-1,"n.a."])
df

  Company    eps  income    Rate        Founder
0   GOOGL  27.82    87.0   845.0     larry page
1     WMT   4.61   484.0    65.0            NaN
2    MSFT    NaN    85.0    64.0     bill gates
3    RIL     NaN    50.0  1023.0  mukesh ambani
4    TATA   5.60     NaN     NaN     ratan tata

In [36]:
df["Pe"] = df["Rate"]/df["eps"]

In [37]:
df

  Company    eps  income    Rate        Founder         Pe
0   GOOGL  27.82    87.0   845.0     larry page  30.373832
1     WMT   4.61   484.0    65.0            NaN  14.099783
2    MSFT    NaN    85.0    64.0     bill gates        NaN
3    RIL     NaN    50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60     NaN     NaN     ratan tata        NaN

In [41]:
df.to_csv("pe1.csv",index = False)

In [48]:
pip list

Package                   Version
------------------------- -----------
anyio                     4.14.2
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.2
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.7.22
cffi                      2.1.0
charset-normalizer        3.4.9
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
et_xmlfile                2.0.0
exceptiongroup            1.3.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.18
ipykernel                 7.3.0
ipython                   8.39.0
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.20.0
Jinja2                    3.1.6
json5                     0.15.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_builder           1.1.1
jupyter_client            8.9.1
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.20.0
jupyter_server_terminals  0.5.4
jupyterlab                4.6.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib-inline         0.2.2
mistune                   3.3.4
nbclient                  0.11.0
nbconvert                 7.17.1
nbformat                  5.10.4
nest-asyncio2             1.7.2
notebook                  7.6.1
notebook_shim             0.2.4
numpy                     2.2.6
openpyxl                  3.1.5
overrides                 7.7.0
packaging                 26.2
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.7
pip                       26.1.2
platformdirs              4.11.0
prometheus_client         0.25.0
prompt_toolkit            3.0.52
psutil                    7.2.2
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.20.0
python-dateutil           2.9.0.post0
python-json-logger        4.1.0
pytz                      2026.4
pywinpty                  3.0.5
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.34.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
Send2Trash                2.1.0
setuptools                65.5.0
six                       1.17.0
soupsieve                 2.9.1
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.5.1
tomli                     2.4.1
tornado                   6.5.7
traitlets                 5.15.1
typing_extensions         4.16.0
tzdata                    2026.3
uri-template              1.3.0
urllib3                   2.7.0
wcwidth                   0.8.2
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15
Note: you may need to restart the kernel to use updated packages.

In [52]:
df_movies = pd.read_excel("movies_db.xlsx","movies")
df_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [58]:
df_finance = pd.read_excel("movies_db.xlsx","financials",header=10)
df_finance
# df_finance.USD.unique()

    111        25      73.3   Millions  USD
0   113    165.00     701.8   Millions  USD
1   114    205.00     365.3   Millions  USD
2   115     55.00     307.1   Millions  USD
3   116    103.00     460.5   Millions  USD
4   117    200.00    2202.0   Millions  USD
5   118      3.18       3.3   Millions  USD
6   119    237.00    2847.0   Millions  USD
7   120      7.20     291.0   Millions  USD
8   121    185.00    1006.0   Millions  USD
9   122     22.00     322.2   Millions  USD
10  123     63.00    1046.0   Millions  USD
11  124     15.50     263.1   Millions  USD
12  125    400.00    2798.0   Millions  USD
13  126    400.00    2048.0   Millions  USD
14  127  70000.00  100000.0  Thousands  INR
15  128    120.00    1350.0   Millions  INR
16  129    100.00     410.0   Millions  INR
17  130    850.00    8540.0   Millions  INR
18  131      1.00       5.9   Billions  INR
19  132      2.00       3.6   Billions  INR
20  133      5.50      12.0   Billions  INR
21  134      1.80       6.5   Billions  INR
22  135    250.00    3409.0   Millions  INR
23  136    900.00   11690.0   Millions  INR
24  137    216.70     370.6   Millions  USD
25  138    177.00     714.4   Millions  USD
26  139      1.80       3.1   Billions  INR
27  140    500.00     950.0   Millions  INR
28  406     30.00     350.0   Millions  INR
29  412    160.00     836.8   Millions  USD

In [64]:
def currency_conv(curr):
    if curr == "INR" or curr == "$$" or curr == "Dollars":
        return "USD"
    return curr
df_finance = pd.read_excel("movies_db.xlsx","financials", converters = {
    'currency' : currency_conv
})
df_finance

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      USD
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions      USD
3        104    180.00     854.0   Millions      USD
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      USD
6        108    550.00    4000.0   Millions      USD
7        109    390.00    1360.0   Millions      USD
8        110      1.40       3.5   Billions      USD
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      USD
25       128    120.00    1350.0   Millions      USD
26       129    100.00     410.0   Millions      USD
27       130    850.00    8540.0   Millions      USD
28       131      1.00       5.9   Billions      USD
29       132      2.00       3.6   Billions      USD
30       133      5.50      12.0   Billions      USD
31       134      1.80       6.5   Billions      USD
32       135    250.00    3409.0   Millions      USD
33       136    900.00   11690.0   Millions      USD
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      USD
37       140    500.00     950.0   Millions      USD
38       406     30.00     350.0   Millions      USD
39       412    160.00     836.8   Millions      USD

In [66]:
df_merged = pd.merge(df_movies,df_finance, on="movie_id")
df_merged

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.00,12.5,Billions,USD
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.00,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.00,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.00,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.00,670.0,Millions,USD
5,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1,400.00,2000.0,Millions,USD
6,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,550.00,4000.0,Millions,USD
7,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1,390.00,1360.0,Millions,USD
8,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1,1.40,3.5,Billions,USD
9,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5,25.00,73.3,Millions,USD
10,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5,165.00,701.8,Millions,USD
11,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5,55.00,307.1,Millions,USD
12,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5,103.00,460.5,Millions,USD
13,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5,200.00,2202.0,Millions,USD
14,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5,3.18,3.3,Millions,USD
15,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5,237.00,2847.0,Millions,USD
16,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5,7.20,291.0,Millions,USD
17,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5,185.00,1006.0,Millions,USD
18,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5,22.00,322.2,Millions,USD
19,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5,63.00,1046.0,Millions,USD
20,124,Parasite,Hollywood,2019,8.5,NaN,5,15.50,263.1,Millions,USD
21,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5,400.00,2798.0,Millions,USD
22,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5,400.00,2048.0,Millions,USD
23,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7,70000.00,100000.0,Thousands,USD
24,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1,120.00,1350.0,Millions,USD
25,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1,100.00,410.0,Millions,USD
26,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1,850.00,8540.0,Millions,USD
27,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1,1.00,5.9,Billions,USD
28,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2,2.00,3.6,Billions,USD
29,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2,5.50,12.0,Billions,USD
30,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2,1.80,6.5,Billions,USD
31,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1,250.00,3409.0,Millions,USD
32,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1,900.00,11690.0,Millions,USD
33,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5,216.70,370.6,Millions,USD
34,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5,177.00,714.4,Millions,USD
35,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1,1.80,3.1,Billions,USD
36,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1,500.00,950.0,Millions,USD

In [68]:
df_merged.to_excel("movies_merged23.xlsx", sheet_name="movies_updated",index=False)

In [81]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [82]:
df.set_index("day",inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [78]:
# df.fillna(0)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [83]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [87]:
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed':df.windspeed.mean(),
    'event':'No event'
})

            temperature  windspeed     event
day
2017-01-01        32.00       6.00      Rain
2017-01-04        33.22       9.00     Sunny
2017-01-05        28.00       8.42      Snow
2017-01-06        33.22       7.00  No event
2017-01-07        32.00       8.42      Rain
2017-01-08        33.22       8.42     Sunny
2017-01-09        33.22       8.42  No event
2017-01-10        34.10       8.10    Cloudy
2017-01-11        40.00      12.00     Sunny

In [91]:
df.fillna(method='ffill', limit=2)

C:\Users\Hp\AppData\Local\Temp\ipykernel_12856\2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [92]:
df.interpolate()

C:\Users\Hp\AppData\Local\Temp\ipykernel_12856\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [97]:
df.dropna(thresh=6)

Empty DataFrame
Columns: [temperature, windspeed, event]
Index: []

In [99]:
df_na = pd.read_csv("weather_data.csv")
df_na

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [101]:
df.replace(-99999,0)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [102]:
df_wc = pd.read_csv("weather_by_cities.csv")
df_wc

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [103]:
wg = df_wc.groupby('city')
wg

In [105]:
for city, data in wg:
    print("City name :",city)
    print("\n")
    print("Data",data)
    print("Max temp :",data.temperature.max())

City name : mumbai


Data         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
Max temp : 92
City name : new york


Data         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
Max temp : 36
City name : paris


Data          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy
Max temp : 54

In [107]:
wg.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [112]:
def groupfnc(df, idx, col):
    if 80<= df[col].loc[idx] <=90:
        return '80-90 range'
    elif 50<= df[col].loc[idx] <=60:
        return '50-60 range'
    else:
        return "Others"

In [117]:
wg = df_wc.groupby(lambda idx: groupfnc(df_wc,idx,'temperature'))
wg

In [120]:
for key , data in wg:
    print("Key", key)
    print("Data",data)

Key 50-60 range
Data          day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
Key 80-90 range
Data         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
Key Others
Data          day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy

In [121]:
pip install matplotlib

Collecting matplotlibNote: you may need to restart the kernel to use updated packages.

  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.65.0-cp310-cp310-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp310-cp310-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.3.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 4.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.2 MB 3.2 MB/s eta 0:00:03
   -------- ------------------------------- 1.8/8.2 MB 2.9 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.2 MB 2.8 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.2 MB 3.0 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.2 MB 3.2 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.2 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.2 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.1 MB/s  0:00:02
Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp310-cp310-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------------- -------------------- 0.8/1.6 MB 1.9 MB/s eta 0:00:01
   ------------------------- -------------- 1.0/1.6 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 2.1 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp310-cp310-win_amd64.whl (70 kB)
Downloading pillow-12.3.0-cp310-cp310-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 1.7 MB/s eta 0:00:05
   ---- ----------------------------------- 0.8/7.2 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/7.2 MB 1.6 MB/s eta 0:00:04
   -------- ------------------------------- 1.6/7.2 MB 1.6 MB/s eta 0:00:04
   ----------- ---------------------------- 2.1/7.2 MB 1.8 MB/s eta 0:00:03
   -------------- ------------------------- 2.6/7.2 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 2.9/7.2 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 3.4/7.2 MB 1.9 MB/s eta 0:00:02
   ----------------------- ---------------- 4.2/7.2 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 4.7/7.2 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 5.2/7.2 MB 2.2 MB/s eta 0:00:01
   ------------------------------ --------- 5.5/7.2 MB 2.2 MB/s eta 0:00:01
   --------------------------------- ------ 6.0/7.2 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 6.3/7.2 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 6.8/7.2 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 6.8/7.2 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 1.9 MB/s  0:00:03
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.10.9 pillow-12.3.0 pyparsing-3.3.3

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax. Perhaps you forgot a comma? (865967143.py, line 1)